function setup() {
  createCanvas(1863, 980);
  getMinMax_Gangwon();
  getMinMax_Gyunggi();
  getMinMax_Gyeongnam();
  getMinMax_Gyeongbuk();
  getMinMax_Gwangju();
  getMinMax_Daegu();
  getMinMax_Daejeon();
  getMinMax_Busan();
  getMinMax_seoul();
  getMinMax_Sejong();
  getMinMax_Ulsan();
  getMinMax_Incheon();
  getMinMax_Jeonnam();
  getMinMax_Jeonbuk();
  getMinMax_Jeju();
  getMinMax_Chungnam();
  getMinMax_Chungbuk();
  getMinMax_Gangwon2();
  getMinMax_Gyunggi2();
  getMinMax_Gyeongnam2();
  getMinMax_Gyeongbuk2();
  getMinMax_Gwangju2();
  getMinMax_Daegu2();
  getMinMax_Daejeon2();
  getMinMax_Busan2();
  getMinMax_seoul2();
  getMinMax_Sejong2();
  getMinMax_Ulsan2();
  getMinMax_Incheon2();
  getMinMax_Jeonnam2();
  getMinMax_Jeonbuk2();
  getMinMax_Jeju2();
  getMinMax_Chungnam2();
  getMinMax_Chungbuk2();
  colorMode(HSB);
}

function draw() {

  textSize(40);
  tint(200, 200, 200);
  image(backImage, 0, 0);
  Gangwon_disp();
  Gyunggi_disp();
  Gyeongnam_disp();
  Gyeongbuk_disp();
  Gwangju_disp();
  Daegu_disp();
  Daejeon_disp();
  Busan_disp();
  Seoul_disp();
  Sejong_disp();
  Ulsan_disp();
  Incheon_disp();
  Jeonnam_disp();
  Jeonbuk_disp();
  Jeju_disp();
  tint(0);
  Chungnam_disp();
   tint(0);
  Chungbuk_disp();
  Gangwon_disp2();
  Gyunggi_disp2();
  Gyeongnam_disp2();
  Gyeongbuk_disp2();
  Gwangju_disp2();
  Daegu_disp2();
  Daejeon_disp2();
  Busan_disp2();
  Seoul_disp2();
  Sejong_disp2();
  Ulsan_disp2();
  Incheon_disp2();
  Jeonnam_disp2();
  Jeonbuk_disp2();
  Jeju_disp2();
  tint(0);
  Chungnam_disp2();
   tint(0);
  Chungbuk_disp2();
  color_bar2(1678, 163, 20);
  color_bar(718, 163, 20);
}
